### ISSUE TITLE
Package empty in PyPi

### ISSUE THREAD

**Issue by gptech** [thearchitector/just-jobs#4]
Hello! I tried installing this library via pip, but the package is empty (only file in the module is py.typed).

Could you take a look?

**Comment by thearchitector** [comment]
@gptech wow what an oversight! I accidentally excluded the actual package from the distribution, but didn't notice because it was cached locally during testing 😅. I republished it under the same version, so you should be able to install it now.

**Comment by thearchitector** [comment]
@gptech confirming if you're able to install so I can close this

**Comment by gptech** [comment]
Sorry for the delay! I was able to install, and it works great!

Awesome library by the way :+1:

**Comment by thearchitector** [comment]
good to know, and thanks!
